### PR TITLE
Added Calls to Support Interrupts and Added Interrupt Example

### PR DESCRIPTION
**Pull request by Vgdn1942**
Updated and clang-format this pull request https://github.com/adafruit/Adafruit_VL53L0X/pull/8

### CODE REVIEW

**Comment by frollard** [comment]
Would love to see this get pulled. Looks good so far. Examples are a bit of a pain because (unless I'm doing it wrong) the library wants to fight with the one from the library manager. 
Excellent work.

**Comment by ladyada** [comment]
@frollard did you try this PR out, does the code work ok? :)

**Comment by caternuson** [comment]
Referring to the VL53L0X state machine flow diagram from the datasheet, and focusing on the steps for making a measurement (rectangle):
image

This library currently combines the mode setting (Range Mode) and range starting (Range Meas) into single methods:

- **Single**: `Adafruit_VL53L0X::startRange()`
- **Continuous Timed**: `Adafruit_VL53L0X::startRangeContinuous()`

The interrupt feature is just a signaling mechanism for the measurement completion (or limits exceeded). There shouldn't be any need for new measurement start/stop methods. I think all that's needed is a new method that exposes VL53L0X_SetGpioConfig() to allow enabling and configuring the interrupt behavior. The rest would be up to user code - to read the interrupt pin, attach it to an ISR, etc. Or am I missing something?

**Comment by frollard** [comment]
> There shouldn't be any need for new measurement start/stop methods.

The only start/stop I can think would be low power/ultra low power instances where the sensor is held in standby most of the time, pinging, then start/stop continuous mode when something is detected to accurately find the 'end' state. I have a hunch the most common diy use case is 'turn on continuous', and ability to switch between the resolution/speed modes. The only example right now is the 'extended' multi which is super overwhelming for someone trying to get a single sensor into continuous mode.
@ladyada I got it to compile but am currently switching from arduino ide to pio...and it's truly a nightmare. Don't rely on me for in depth testing in the immediate term.

**Comment by frollard** [comment]
Finally got this running; tldr: continuous mode doesn't seem to fire continuously and my code is so bad I don't know if I'm doing it wrong. 
setup vl53l0x in continuous, fast mode, new measurement ready interrupt
isr monitors interrupt, sets flag
main loop checks flag to take reading and act on it for non-blocking operation, clears flag.

If I move the checking for reading to the isr flag function, it takes one measurement then the isr never fires again. - as if 
` rawSensorRange = vl.readRange() + mmOffset;
  byte status = vl.readRangeStatus();`
doesn't clear the interrupt register properly on the first go around.

If I always check for a measurement every loop, the measurements of course work, AND the isr triggers just prior to each measurement coming in over &wire.
I wish I had the vocabulary to explain why I think something isn't 100% right. The readRange method seems to reset the interrupt flags so I don't know why it fails.

**Comment by frollard** [comment]
Did a bunch of testing, wrote a long reply, and it's vanished.

Setting to continuous mode with gpio in 'new measurement ready interrupt' I only get 1 reading back; the interrupt triggers and sets an isr flag, the main loop detects the flag, queries the reading then resets the interrupt mask (which should enable the next trigger)...but it just stops interrupting. 
If I have the main loop ignore the reading-ready isr flag and just poll the chip on every loop, it comes back with a new reading every 50ms or so (which seems very slow for setting the chip to 'high speed' mode.  Will investigate further and come back with something more concrete.

**Pull request merged**
