### PR TITLE
Added Calls to Support Interrupts and Added Interrupt Example

### PR DESCRIPTION
**Pull request by Andrewiski**
I have exposed some additional underlying ST API calls to support Interrupts and added a simple example on how to use the VL53L0X to trigger an Interrupt when an object is measured below the set threshold.

Thanks for all you guys do to support the open source community, Adafruit rocks.

### CODE REVIEW

**Comment by zpowellman** [comment]
This update is potentially very useful for VL53L0X users.  What's the status of this update?  Is the author still involved in this project?
One thing missing from all libraries is interrupt capability.  This certainly fills the bill.  Thanks Andrew.  Nice job

**Comment by ladyada** [comment]
there's a merge conflict, it needs work before it can be merged!

**Comment by Andrewiski** [comment]
I did a pull from the upstream and merged in my changes, I am on the road and do not have a single dev kit with me so only check I could do was to compile, anyways the code changes were all adds of new methods with no changes to existing so low risk for breaking changes. Changes are trivial add of additional i2c calls to support interrupts.  

Thanks Lady Ada and Adafruit for all you do

**Comment by Andrewiski** [comment]
How do I get more information regarding the clang exit code that is failing in the build above?

**Comment by ladyada** [comment]
please run `clang-format` on your files 
https://github.com/adafruit/Adafruit_VL53L0X/runs/972132883
https://www.kernel.org/doc/html/latest/process/clang-format.html

**Comment by JackBonnellDevelopment** [comment]
Whoever Ladyada is needs to get their finger out with this merger. @Andrewiski Currently designing bi-directional counting sensors for a client and your work was very helpful and is much appreciated.

**Comment by caternuson** [comment]
Closing this one in favor of #49.

**Pull request closed without merging**
